export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS';
export const CUSTOMER_REGISTER_FAILED = 'CUSTOMER_REGISTER_FAILED';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAILED = 'CUSTOMER_LOGIN_FAILED';

export const SHOW_LOGIN_POPUP = 'SHOW_LOGIN_POPUP';
export const HIDE_LOGIN_POPUP = 'HIDE_LOGIN_POPUP';

export const SHOW_REGISTER_POPUP = 'SHOW_REGISTER_POPUP';
export const HIDE_REGISTER_POPUP = 'HIDE_REGISTER_POPUP';

export const SHOW_PROFILE_POPUP = 'SHOW_PROFILE_POPUP';
export const HIDE_PROFILE_POPUP = 'HIDE_PROFILE_POPUP';

export const CUSTOMER_GET_SUCCESS = 'CUSTOMER_GET_SUCCESS';
export const CUSTOMER_GET_FAILURE = 'CUSTOMER_GET_FAILURE';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';



export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const SHOW_PRODUCT_POPUP = 'SHOW_PRODUCT_POPUP';
export const HIDE_PRODUCT_POPUP = 'HIDE_PRODUCT_POPUP';



export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';
export const GET_CART_PRODUCTS_SUCCESS = 'GET_CART_PRODUCTS_SUCCESS';
export const GET_CART_PRODUCTS_FAILURE = 'GET_CART_PRODUCTS_FAILURE';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const HAS_DEFFERENT_SHIPPING_ADDRESS = 'HAS_DEFFERENT_SHIPPING_ADDRESS';

export const SET_STRIPE_CLIENT_SECRET = 'SET_STRIPE_CLIENT_SECRET'; 

export const SET_MY_ORDERS = 'SET_MY_ORDERS';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';