export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS';
export const CUSTOMER_REGISTER_FAILED = 'CUSTOMER_REGISTER_FAILED';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAILED = 'CUSTOMER_LOGIN_FAILED';

export const SHOW_LOGIN_POPUP = 'SHOW_LOGIN_POPUP';
export const HIDE_LOGIN_POPUP = 'HIDE_LOGIN_POPUP';

export const SHOW_REGISTER_POPUP = 'SHOW_REGISTER_POPUP';
export const HIDE_REGISTER_POPUP = 'HIDE_REGISTER_POPUP';

export const SHOW_PROFILE_POPUP = 'SHOW_PROFILE_POPUP';
export const HIDE_PROFILE_POPUP = 'HIDE_PROFILE_POPUP';

export const CUSTOMER_GET_SUCCESS = 'CUSTOMER_GET_SUCCESS';
export const CUSTOMER_GET_FAILURE = 'CUSTOMER_GET_FAILURE';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';



export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const SHOW_PRODUCT_POPUP = 'SHOW_PRODUCT_POPUP';
export const HIDE_PRODUCT_POPUP = 'HIDE_PRODUCT_POPUP';